### PR TITLE
Save Data Rewrite V2

### PR DESCRIPTION
**Pull request by Joalor64**
first one broke, so here's a new one

### CODE REVIEW

**Comment by Joalor64** [comment]
hey umm @GuineaPigUuhh if you're not busy atm, could you help fix an issue in `ControlsSubState`?

**Comment by moxie-coder** [comment]
> hey umm @GuineaPigUuhh if you're not busy atm, could you help fix an issue in `ControlsSubState`?

huh, what issue?

**Comment by Joalor64** [comment]
```
Exception: Null Object Reference
states/substates/ControlsSubState.hx (line 94)
flixel/FlxState.hx (line 239)
flixel/FlxState.hx (line 248)
flixel/FlxGame.hx (line 750)
```

line 94, apparently

**Comment by guineapiguuhh** [comment]
@Joalor64GH sorry for the delay, I'll see what I can do 👍

**Comment by guineapiguuhh** [comment]
@Joalor64GH fix

`SaveData.hx`
```haxe
package backend.data;

@:structInit class SaveSettings {
	public var timeFormat:String = '%r';
	public var theme:String = 'daylight';
	public var lang:String = 'en';
	public var username:String = 'user';
	public var profile:String = 'blue';
	public var framerate:Int = 60;
	public var colorBlindFilter:Int = -1;
	public var fpsCounter:Bool = true;
	#if desktop
	public var fullscreen:Bool = false;
	#end
	public var keyboardBinds:Array<FlxKey> = [LEFT, DOWN, UP, RIGHT, ENTER, ESCAPE];
	public var gamepadBinds:Array<FlxGamepadInputID> = [DPAD_LEFT, DPAD_DOWN, DPAD_UP, DPAD_RIGHT, A, B];
}

class SaveData {
	public static var settings:SaveSettings = {};

	public static function init() {
		for (key in Reflect.fields(settings))
			if (Reflect.field(FlxG.save.data, key) != null)
				Reflect.setField(settings, key, Reflect.field(FlxG.save.data, key));
		
		if (Main.fpsDisplay != null)
			Main.fpsDisplay.visible = settings.fpsCounter;
		
		Main.updateFramerate(settings.framerate);
	}

	public static function saveSettings() {
		for (key in Reflect.fields(settings))
			Reflect.setField(FlxG.save.data, key, Reflect.field(settings, key));

		FlxG.save.flush();

		trace('settings saved!');
	}
}

```

**Comment by Joalor64** [comment]
thx dude 😁

**Pull request merged**
